import type { Metadata } from "next";
import {Poppins } from "next/font/google";
import "./globals.css";
import { Provider } from "./provider";
import { Toaster } from "sonner";

const poppins = Poppins({subsets : ['latin'] , weight:['200','400','700']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.className} antialiased`}
      >
        <Provider>
          <Toaster position="top-right"/>
        {children}
        </Provider>
      </body>
    </html>
  );
}
